---
title: "Addit. Info"
author: "James Welch, iGEM Women in STEM"
date: "7/8/2021"
output: html_document
---
# UNESCO Data Explanation

### [UNESCO Data Explorer](http://data.uis.unesco.org/)
                    

## DATASETNAME_LABEL.csv
This file is a list of all indicator codes and their descriptive labels:

|Field Name|Field Description|
|---|---|
|INDICATOR_ID |Indicator code|
|INDICATOR_LABEL_EN|Indicator code English label|

## DATASETNAME_DATA_NATIONAL.csv
This file contains all the national data available for this dataset and includes the following fields: 

|Field Name|Field Description|
|---|---|
|INDICATOR_ID|Indicator code|
|COUNTRY_ID|ISO 3166-1 alpha-3 country code|
|YEAR |Year of the measured value|
|VALUE |Measured value|
|MAGNITUDE |Metadata describing the NATURE of the measured value (see metadata section below)|
|QUALIFIER|Metadata describing the QUALITY of the measured value (see metadata section below)|

## DATASETNAME_DATA_REGIONAL.csv
This file contains all the regional data available for this dataset and includes the following fields: 

|Field Name|Field Description|
|---|---|
|INDICATOR_ID|Indicator code|
|REGION_ID|ISO 3166-1 alpha-3 country code|
|YEAR |Year of the measured value|
|VALUE |Measured value|
|MAGNITUDE |Metadata describing the NATURE of the measured value (see metadata section below)|
|QUALIFIER|Metadata describing the QUALITY of the measured value (see metadata section below)|


## DATASETNAME_METADATA.csv
This file contains all the metadata associated to the NATIONAL and REGIONAL data files above and includes the following fields: 

|Field Name|Field Description|
|---|---|
|INDICATOR_ID|Indicator code|
|COUNTRY_ID|ISO 3166-1 alpha-3 country code|
|YEAR |Year of the metadata value|
|TYPE |Type of metadata|
|METADATA|Metadata value|

## DATASETNAME_COUNTRY.csv
This file lists all country codes and their descriptive labels:

|Field Name|Field Description|
|---|---|
|COUNTRY_ID|ISO 3166-1 alpha-3 country code|
|COUNTRY_NAME_EN|UNSTATS M49 STANDARD English country name|
(https://unstats.un.org/unsd/methodology/m49/)

## DATASETNAME_REGION.csv (not currently supported)
This file lists all regions and the countries that belong to each region:

|Field Name|Field Description|
|---|---|
|REGION_ID|Label is composed of the name (acronym) of the organization that is responsible for the regional composition + ': ' + name of the region
|COUNTRY_ID|ISO 3166-1 alpha-3 country code|
|COUNTRY_NAME_EN|UNSTATS M49 STANDARD English country name|
(https://unstats.un.org/unsd/methodology/m49/)

 Metadata
## Indicator Metadata
Most indicators have a Glossary entry that can be accessed on the [UIS website](http://uis.unesco.org/en/glossary) containing the indicators: definition, interpretation, purpose, quality standards, calculation, types of disaggregation and limitation.

## Magnitude
MAGNITUDE describes the NATURE of the data point. Possible values are: 
- **NIL**  The value will be 0, and should be treated as NIL.
- **NA**  The value will be 0.  This data point is NOT APPLICABLE for the submitting nation.
- **SUPP** -  The value will be BLANK.  The data point was SUPPRESSED by request of the submitting nation.
- **LOWREL**  The value will be NUMERIC.  The data point is of LOW RELIABILITY.
- **INCLUDED**  The value will be BLANK. This data is INCLUDED in ANOTHER data point.
- **INCLUDES**  The value will be NUMERIC.  This data point INCLUDES data from another data point.

## Qualifier
QUALIFIER describes the QUALITIES of the data point. Possible values are:
- **NAT_EST**  The value will be NUMERIC.  This data point is a NATIONAL ESTIMATE.
- **UIS_EST**  The value will be NUMERIC.  This data point is an ESTIMATE produced by the UNESCO INSTITUTE FOR STATISTICS.